import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { ThemeProvider } from "./theme-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider>
      <body
        className={` antialiased`}
      >
        <nav className="flex justify-between backdrop-blur-sm z-50 items-center gap-4 px-3 h-20 w-full bg-black/15 shadow dark:bg-white/70 font-bold sticky top-0 left-0">
        <Image src="/logo2.png" height={800} width={800} className="h-full w-20 rounded-full" alt="" />
        <ul className="flex justify-between items-center gap-3">
          <li className="text-cyan-500 bg-clip-text text-shadow-[0_0_2px_black] group relative"><div className="absolute bottom-0 left-0 h-0.5 w-0 bg-yellow-500 group-hover:w-full transition-all duration-300"></div><Link href="/">Home</Link></li>
          <li className="text-cyan-500 bg-clip-text text-shadow-[0_0_2px_black] group relative"><div className="absolute bottom-0 left-0 h-0.5 w-0 bg-yellow-500 group-hover:w-full transition-all duration-300"></div><Link href="/about">About</Link></li>
        </ul>
        </nav>
        {children}
      </body>
      </ThemeProvider>
    </html>
  );
}
